name: talk_ami_app
description: Flutter app that loads talk.ami-intelligente.com
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.14.0
  animated_background: ^2.0.0
  connectivity_plus: ^7.0.0
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  shared_preferences: ^2.2.0
  http: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icone_green3.jpeg
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icone_green3.jpeg"
